### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by banacorn** [banacorn/agda-mode#28]
## To-do

- [x] setup testing environment
  - [x] [customize testing suite](https://github.com/atom/atom/pull/8968) (arguably the most difficult part, screw Jasmine, now we use [Mocha](mochajs.org))
- [x] continuous integration
  - [x] hook up with [Travis CI](https://travis-ci.org/banacorn/agda-mode) (test drive on branch [spec](https://github.com/banacorn/agda-mode/branches))
  - [x] [dockerize](https://hub.docker.com/r/banacorn/agda/) Agda
  - [ ] target OS X and Windows
- [ ] actually write down the tests
  - [x] package activation
  - [ ] others

**Comment by omega12345** [comment]
What's the status on this one? It struck me while I was blundering about breaking stuff that you get a fair few tests for free that way. I don't quite know enough about Atom packages to figure out how to format tests, though.

**Comment by banacorn** [comment]
There are many test suites (Jasmine, Mocha, Jest ...). In theory we can use any of the suite we like to write tests. However, some tests require bindings to Atom, and Atom only "supports" an old version of Jasmine, other suites would require some addition machinery.

The suite I'm prefer is Jest (works great with React, has Reasonml binding ...), but the binding is either [unmaintained and dunno how to use](https://github.com/facebookarchive/nuclide/tree/master/modules/jest-atom-runner), or [broken](https://github.com/keplersj/atom-test-runner-jest). I think I can get this to work given I have enough time. But perhaps I should just stop using this as an excuse and starting writing unit tests that doesn't require Atom anyway :)
